version: '3'
services:
  db:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ductvh-wsm
    ports:
      - "3308:3306"
    volumes:
      - mysql_data:/var/lib/mysql
  app:
    build: .
    command: npm run start:dev
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db
volumes:
  mysql_data:
  app:
    driver: local