version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test
    ports:
      - "3306:3306"
  app:
    build: .
    command: npm start
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    depends_on:
      - db